services:
  ai:
    build:
      context: ./  # AI 서버 코드가 있는 디렉토리 경로
    container_name: classlog-ai
    ports:
      - "8000:8000"  # AI 서버 포트
    networks:
      - classlog-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_API_KEY=${OPENAI_API_KEY}
      
networks:
  classlog-network:
    driver: bridge