services:
  ai:
    build:
      context: ./  # AI 서버 코드가 있는 디렉토리 경로
    container_name: classlog-ai
    ports:
      - "8000:8000"  # AI 서버 포트
    networks:
      - classlog-network
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}  # OpenRouter API Key (환경 변수에서 가져오기)
      - WHISPER_API_KEY=${WHISPER_API_KEY}  # Whisper API Key (환경 변수에서 가져오기)

networks:
  classlog-network:
    driver: bridge